### ISSUE TITLE
Example output

### ISSUE THREAD

**Issue by robertlevy** [cloudflare/json-schema-docs-generator#1]
Could you provide an example of the generated output?

**Comment by Relequestual** [comment]
Any plans to continue with this project, or is it defunct?

**Comment by toekneestuck** [comment]
I have a large pull request open [here](https://github.com/cloudflare/json-schema-docs-generator/pull/6) that is a significant refactor of what's here currently. It's far more complete with a full test suite and separating functionality into individual components to hopefully allow this project to become more flexible and extensible. 

It's not perfect by any means, but should be a big improvement over the current state. It's not quite complete though; specifically I'm looking for ideas/thinking of how to design the composition of templates and schemas into pages and navigation. If you have any ideas, feel free to chime in :)

**Comment by Relequestual** [comment]
I'd be tempted to suggest doing something similar to Slate (documentation generator). If it wasn't for the fact that it assumes you'll have sample code, I'd probably suggest it for this.

Hum. It's difficult. I'm not really sure. Trouble is you can't make any assumptions about how many of anything there is with the schemas.

You could require that the json-schema files are in a hierarchie. I can't work out if I'm for or against single page API documentation. It would make it a lot easier at this point I'd guess.
