### ISSUE TITLE
Suggestion: Use array instead of object for requiredProps in endpoint template 

### ISSUE THREAD

**Issue by swamikevala** [cloudflare/json-schema-docs-generator#10]
Since Handlebars treats empty object {} as truthy, we end up getting "Required / Optional Properties" headings, even if there are no properties.

If these were stored as arrays then they would not be displayed. Or if the object was deleted if empty

**Comment by tajo** [comment]
This has been changed (https://github.com/cloudflare/json-schema-docs-generator/pull/26). When empty it returns `null`.
