### ISSUE TITLE
Markdown not parsed for description key on main resource JSON object

### ISSUE THREAD

**Issue by iToto** [cloudflare/json-schema-docs-generator#16]
The Markdown embedded in the description does not get parsed properly: 

```json
{
  "id": "/myResource",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "My Resource",
  "description": "This is my resource **API** doc. And here is a link: [link text](#anchor)",
  "type": "object"
}
```

Is rendered as a literal string:

`This is my resource **API** doc. And here is a link: [link text](#anchor)`

**Comment by tajo** [comment]
(This lib doesn't support markdown out of the box now. However, you can solve it with a handlebar helper.)
