### ISSUE TITLE
templates.base is not a function

### ISSUE THREAD

**Issue by tehaaron** [cloudflare/json-schema-docs-generator#17]
I am trying to run the example `node bin.js` but when I do I receive the error "templates.base is not a function". I installed via `npm install json-schema-docs-generator` and moved the bin.js and schema folder to the root directory. This also required changing this bin.js line:
`var templateDriver = new Docs.TemplateDriver(['node_modules/json-schema-docs-generator/themes/bootstrap/*.handlebars']` 

It could be my inexperience with node programs like these since when I looked at `lib/composer.js` and `drivers/template.js` I didn't see anything immediately wrong.

**Comment by tajo** [comment]
You also need to move `/themes/bootstrap` folder (templates) and fix paths. However, it's going to be easier with https://github.com/cloudflare/json-schema-docs-generator/pull/29 ... (README updated).
