### ISSUE TITLE
Improperly resolving rel:self references

### ISSUE THREAD

**Issue by toekneestuck** [cloudflare/json-schema-docs-generator#2]
When defining an attribute as an array with items being a reference to itself, it fails. Even referencing `"$ref": "#"` results in a max call stack error. This is when defined in a `link` object.

```javascript
{
    "properties": {
         "items": {
             "type": "array",
             "items": {"rel": "self"}
          }
    }
}
```
and
```javascript
{
    "properties": {
         "items": {
             "type": "array",
             "items": {"$ref": "#"}
          }
    }
}
```
both fail.

**Comment by swamikevala** [comment]
Any idea when this might be fixed? Am having the same issue

**Comment by tajo** [comment]
It should fixed with https://github.com/cloudflare/json-schema-docs-generator/pull/28.
