### ISSUE TITLE
"Show definition" feature for  sub-objects not working 

### ISSUE THREAD

**Issue by swamikevala** [cloudflare/json-schema-docs-generator#9]
version 1.0.3

Sub-object expansion feature is not working.

Have attached modified example bin.js and product schema to illustrate this
[bin.js.txt](https://github.com/cloudflare/json-schema-docs-generator/files/84117/bin.js.txt)

[product.json.txt](https://github.com/cloudflare/json-schema-docs-generator/files/84120/product.json.txt)

Also, the example string for an object property only appears if I have an "id" property on that object, otherwise it is "{ }". I wouldn't want to set ids on all my sub-objects for this to work.

Amazing project BTW. Exactly what I was searching for.

Kind Regards
Swami Kevala

**Comment by tajo** [comment]
Can you try the latest version? It might be ok now.

**Comment by handrews** [comment]
This project has been replaced by doca, and this feature is tracked at cloudflare/doca#17
